### ISSUE TITLE
[Bug]: Tabs在Transition mitigation下渲染时其它的tab的内容也会短暂的出现

### ISSUE THREAD

**Issue by Zz-ZzzZ** [any-tdf/stdf#17]
### 模块

Tabs
### 版本

doc demo

### 描述缺陷

Tabs在Transition mitigation下渲染时其它的tab的内容也会短暂的出现

### 复现

手机真机预览或doc内都可以复现

https://stdf.design/#/components?nav=tabs&tab=0

### 你的想法

启用过渡动画时其它tab应隐藏

**Comment by dufu1991** [comment]
不是很理解你这个描述，麻烦将复现情况描述清楚一点。

**Comment by Zz-ZzzZ** [comment]
![w4oqa-kupu7](https://github.com/any-tdf/stdf/assets/48228016/c142630a-33bc-4437-94cd-d61641d38092)

**Comment by Zz-ZzzZ** [comment]
看了一下代码，是`transition-all`这个属性影响到了，`width`的变更也触发了过渡动画，改为`transition: left`就可以，不过我看`tailwindcss`自带的没有这个属性，就不知道怎么改了。

**Comment by dufu1991** [comment]
这个问题我已经改好了，正在增强 Tabs 组件的其他功能，后续一并发版。

**Comment by dufu1991** [comment]
v0.4.3 已经修复。https://github.com/any-tdf/stdf/commit/5fb915dbc5da00ee466077f1cc1ed0890ae3895d
