### ISSUE TITLE
[Feature]: 请问支持svelte5吗

### ISSUE THREAD

**Issue by graphsay** [any-tdf/stdf#18]
### 模块

stdf (STDF 组件)

### 新功能描述

请问stdf能否在svelte5上使用

**Comment by dufu1991** [comment]
按照 Svelte 官方说法，新版本是向下兼容的，即 Svelte5 是可以兼容 Svelte3/4 的语法的。我使用最新的预览版 ^5.0.0-next.26 简单跑了一下 https://github.com/any-tdf/demo-stdf，未发现异常，但是我未做全面测试。

因为目前官方还未发布正式版，可能还有一些问题未完美解决，肯定还会存在兼容性问题。

**Comment by dufu1991** [comment]
如果你感兴趣的话，可以自己 clone https://github.com/any-tdf/demo-stdf 并升级 Svelte 到 5 的预览版测试。

**Comment by manortec** [comment]
非常感谢，我简单的试了一下，看上去是兼容的。我会试着用svelte5和stdf做一个个人项目，如果有兼容问题，我会记录并发出来，希望在svelte5正式发布之前，这个svelte4分支能渐进的与svelte5兼容。

**Comment by graphsay** [comment]
非常感谢，我简单的试了一下，看上去是兼容的。我会试着用svelte5和stdf做一个个人项目，如果有兼容问题，我会记录并发出来，希望在svelte5正式发布之前，这个svelte4分支能渐进的与svelte5兼容。

**Comment by dufu1991** [comment]
目前 next 版本已经完整支持 Svelte5，请食用。
