### ISSUE TITLE
[Bug]: When execute the command 'npm create stdf@latest', it throws an error

### ISSUE THREAD

**Issue by zfz193071** [any-tdf/stdf#20]
### Module

create (create-stdf scaffolding)

### Bug Description

![image](https://github.com/any-tdf/stdf/assets/159027354/7db3d8e9-ac41-4978-9ee7-ca93f7277e4e)

### Reproduction

on windows

**Comment by dufu1991** [comment]
Do you use 'git bash' or 'CMD' on Windows? If it is wrong to use 'git bash', then try 'CMD' instead?

**Comment by dufu1991** [comment]
Hello, has your problem been solved?
