### ISSUE TITLE
[Feature]: 可否在Calendar中增加年选择，以及多年的月份日期选择

### ISSUE THREAD

**Issue by Haris-ha** [any-tdf/stdf#24]
### 模块

stdf (STDF 组件)

### 新功能描述

可否在Calendar中增加年选择，以及多年的月份日期选择，支持190001-209912，现在无此功能，只有前六个月后六个月，且不支持跳转年份选择只可以滚动，我尝试修改源码，但受限于渲染瓶颈，导致组件卡死。

**Comment by dufu1991** [comment]
1. 只使用年选择可以将 type 设置为 "Y"，	`<TimePicker type="Y" />`。
2. 多年份日期选择，可以传入年份区间，如 `<TimePicker  yearRange={[1900, 2099]} />`，如果只需要选择年月可以将 type 设置为 "YM"。1900-2099 也就差不多 200 行数据，一般来说这点数据渲染页面，不至于卡死。

上述需求通过现有 API 都是可以满足的，也有可能我没完全理解你的需求，如果是，麻烦再描述详细一些。

**Comment by Haris-ha** [comment]
感谢您的回复，我已理解您的设计理念，我会进行组件更换
