### ISSUE TITLE
[Bug]: Icon 添加 click 事件无效

### ISSUE THREAD

**Issue by jiangzimao** [any-tdf/stdf#25]
### 模块

stdf (STDF 组件)

### 版本

0.4.6

### 描述缺陷

当我想给 Icon 绑定一个 click 事件时，发现点击图标后没有反应。以下是我测试的代码：
`<Icon name='ri-chrome-fill' on:click={()=>{alert('test')}} />`

### 复现

给 Icon 绑定一个事件, 点击无效

**Comment by dufu1991** [comment]
一般来说，如果需要给 Icon 绑定事件，建议在外层包裹一下父元素，div 或者 span 都行，在父元素上写事件。建议 Icon 主要用来展示，比如 Icon 很小的时候，移动端手指交互，在很小的元素上绑定事件会影响操作体验。
