### ISSUE TITLE
[Bug]: Button使用injClass注入css,权重会没有默认样式大、会

### ISSUE THREAD

**Issue by gyf3154** [any-tdf/stdf#27]
### 模块

stdf (STDF 组件)

### 描述缺陷

Button使用injClass注入css, bg背景颜色权重会没有默认样式大、会无效

### 复现

![1717141170266](https://github.com/any-tdf/stdf/assets/87295332/fd3d6303-a140-4996-b1e7-1eabd725f066)

**Comment by dufu1991** [comment]
试试文档中的这个方式。https://arc.net/l/quote/wmipbhwj

**Comment by dufu1991** [comment]
能否解决？

**Comment by gyf3154** [comment]
> 能否解决？

已解决
