### ISSUE TITLE
[Feature]: numKeyboard reset value

### ISSUE THREAD

**Issue by sbscan** [any-tdf/stdf#36]
### Module

stdf (STDF component)

### Feature Description

When I user NumKeyboard for multiple input in a page numStr never reset.

### Example

I enter 123 for first field and hit done. For second field when I start hitting it continue from 123. This behaviour is sometimes good sometimes bad. We should have an option to reset value.

### Your Idea

1) We can reset the value when done
2) We can make a method to reset value

**Comment by dufu1991** [comment]
Good idea, I'll add this feature.

**Comment by dufu1991** [comment]
This feature has been completed in v1.0.0-next.9. https://github.com/any-tdf/stdf/releases/tag/v1.0.0-next.9
